title: Wonkes
description: A Marketplace for UH Manoa Students
google_analytics: 
show_downloads: false
theme: jekyll-theme-architect
github:
  is_project_page: true
  is_user_page: false
  repository_url: https://github.com/wonkes-manoa/wonkes-manoa.github.io
gems:
  - jekyll-mentions
